ALTER TABLE clinics ADD COLUMN IF NOT EXISTS telegram_chat_id VARCHAR;
ALTER TABLE clinics ADD COLUMN IF NOT EXISTS report_frequency VARCHAR DEFAULT 'daily';
ALTER TABLE clinics ADD COLUMN IF NOT EXISTS report_time TIME DEFAULT '18:00';
